### ISSUE TITLE
Importing 'vuex-composition-helpers/dist' doesn't work

### ISSUE THREAD

**Issue by exophunk** [greenpress/vuex-composition-helpers#26]
I try to use the library in a Nuxt project. I am not using Typescript so according to the readme I tried:

```javascript
import { createNamespacedHelpers } from 'vuex-composition-helpers/dist';

const { useState, useMutations } = createNamespacedHelpers('connections');
```

which throws an error: `Unexpected token 'export'`

Would I still have to do some manual webpack magic to make it work for a non-ts project?

**Comment by davidmeirlevy** [comment]
Hi,

Here's an example on a Nuxt project config:

https://github.com/greenpress/blog-front/blob/master/nuxt.config.js
See that it was added in line 73 to the build transpile.

That's because the dist transpiled to "esnext", which is good for a frontend project using webpack, but needs an extra traspile at a project that should also run at the backend side.

Hope I helped!
